#!/usr/bin/env php
<?php

declare(strict_types=1);

/**
 * This file is part of the guanguans/laravel-exception-notify.
 *
 * (c) guanguans <ityaozm@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled.
 */

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Process\PhpExecutableFinder;
use Symfony\Component\Process\Process;

require __DIR__.'/vendor/autoload.php';

(new class {
    private SymfonyStyle $symfonyStyle;
    private string $composerJsonFile;
    private string $composerBinary;
    private string $highestComposerBinary;
    private array $exceptPackageNames;
    private array $exceptPackageDependentVersions;
    private bool $verbose;

    public function __construct()
    {
        $this->symfonyStyle = new SymfonyStyle(new ArgvInput, new ConsoleOutput);
        $this->composerJsonFile = __DIR__.'/composer.json';
        $this->composerBinary = $this->findComposerBinary();
        $this->highestComposerBinary = $this->findComposerBinary('/opt/homebrew/opt/php@8.3/bin/php');
        $this->exceptPackageNames = [
            'php',
            'ext-*',
            'laravel/lumen-framework',
            'orchestra/testbench',
            'pestphp/pest-plugin-laravel',
        ];
        $this->exceptPackageDependentVersions = [
            '\*',
            '*-*',
            '*@*',
            // '*|*',
        ];
        $this->verbose = false;
    }

    public function __invoke(): void
    {
        $this
            ->updateComposerPackages()
            ->updateOutdatedComposerPackages()
            ->updateComposerPackages()
            ->normalizeComposerJson()
            ->success();
    }

    private function updateComposerPackages(): self
    {
        $this->mustRunCommand("$this->composerBinary update -W --ansi -v");

        return $this;
    }

    /**
     * @noinspection JsonEncodingApiUsageInspection
     */
    private function updateOutdatedComposerPackages(): self
    {
        file_put_contents(
            $this->composerJsonFile,
            json_encode(
                $this->getOutdatedDecodedComposerJson(),
                JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
            ).PHP_EOL
        );

        return $this;
    }

    private function normalizeComposerJson(): self
    {
        $this->mustRunCommand("$this->composerBinary normalize --diff --ansi -v");

        return $this;
    }

    private function success(): void
    {
        $this->symfonyStyle->success('Composer packages updated successfully!');

        exit(0);
    }

    /**
     * @noinspection JsonEncodingApiUsageInspection
     */
    private function getOutdatedDecodedComposerJson(): array
    {
        $outdatedComposerPackages = $this->getOutdatedComposerPackages();
        $this->symfonyStyle->listing(array_map(
            static fn (array $package): string => "{$package['name']}: {$package['dependency_version']}",
            $outdatedComposerPackages
        ));

        $decodedComposerJson = json_decode(file_get_contents($this->composerJsonFile), true);

        foreach ($decodedComposerJson as $name => &$value) {
            if (! in_array($name, ['require', 'require-dev'], true)) {
                continue;
            }

            foreach ($value as $package => &$dependencyVersion) {
                if (
                    $this->strIs($this->exceptPackageNames, $package)
                    || $this->strIs($this->exceptPackageDependentVersions, $dependencyVersion)
                ) {
                    continue;
                }

                if (isset($outdatedComposerPackages[$package])) {
                    $dependencyVersion = $outdatedComposerPackages[$package]['dependency_version'];
                } else {
                    if (
                        $this->strIs('*|*', $dependencyVersion)
                        || ($version = Composer\InstalledVersions::getVersion($package))
                    ) {
                        continue;
                    }

                    $dependencyVersion = $this->toDependencyVersion($this->toArrayVersion($version));
                }
            }
        }

        return $decodedComposerJson;
    }

    /**
     * @noinspection JsonEncodingApiUsageInspection
     */
    private function getOutdatedComposerPackages(): array
    {
        return array_reduce(
            json_decode(
                $this
                    ->mustRunCommand("$this->highestComposerBinary outdated --format=json --direct --ansi -v")
                    ->getOutput(),
                true
            )['installed'],
            function (array $carry, array $package): array {
                $lowestArrayVersion = $this->toArrayVersion($package['version']);
                $highestArrayVersion = $this->toArrayVersion($package['latest']);

                $dependencyVersions = [$this->toDependencyVersion($package['version'])];
                if ($lowestArrayVersion[0] !== $highestArrayVersion[0]) {
                    $dependencyVersions = array_merge($dependencyVersions, array_map(
                        static fn (string $major): string => "^$major.0",
                        range($lowestArrayVersion[0] + 1, $highestArrayVersion[0])
                    ));
                }

                $package['dependency_version'] = implode(' || ', $dependencyVersions);

                $carry[$package['name']] = $package;

                return $carry;
            },
            []
        );
    }

    private function toArrayVersion(string $version): array
    {
        return explode('.', ltrim($version, 'v'));
    }

    private function toDependencyVersion(string $version): string
    {
        return '^'.implode('.', array_slice($this->toArrayVersion($version), 0, 2));
    }

    private function findComposerBinary(?string $phpBinary = null): string
    {
        return sprintf(
            '%s %s',
            $phpBinary ?? (new PhpExecutableFinder)->find(),
            (new Symfony\Component\Process\ExecutableFinder)->find('composer')
        );
    }

    /**
     * @param array|string $command
     * @param mixed $input The input as stream resource, scalar or \Traversable, or null for no input
     *
     * @noinspection MissingParameterTypeDeclarationInspection
     * @noinspection PhpSameParameterValueInspection
     */
    private function mustRunCommand(
        $command,
        ?string $cwd = null,
        ?array $env = null,
        $input = null,
        ?float $timeout = 60
    ): Process {
        $process = is_string($command)
            ? Process::fromShellCommandline($command, $cwd, $env, $input, $timeout)
            : new Process($command, $cwd, $env, $input, $timeout);

        $this->symfonyStyle->warning($process->getCommandLine());

        return $process
            ->setWorkingDirectory(dirname($this->composerJsonFile))
            ->setEnv(['COMPOSER_MEMORY_LIMIT' => -1])
            ->mustRun(function (string $type, string $buffer): void {
                $this->verbose and $this->symfonyStyle->write($buffer);
            });
    }

    /**
     * @param array|string $pattern
     *
     * @noinspection SuspiciousLoopInspection
     * @noinspection ComparisonScalarOrderInspection
     * @noinspection MissingParameterTypeDeclarationInspection
     */
    private function strIs($pattern, string $value): bool
    {
        $patterns = (array) $pattern;
        if (empty($patterns)) {
            return false;
        }

        foreach ($patterns as $pattern) {
            $pattern = (string) $pattern;
            if ($pattern === $value) {
                return true;
            }

            $pattern = preg_quote($pattern, '#');
            $pattern = str_replace('\*', '.*', $pattern);
            if (1 === preg_match('#^'.$pattern.'\z#u', $value)) {
                return true;
            }
        }

        return false;
    }
})();
